ALTER TABLE knowledge_documents
    ADD COLUMN IF NOT EXISTS source_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS status VARCHAR(64) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS uploaded_by VARCHAR(128),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
