apiVersion: v1
kind: Service
metadata:
  name: aichatbot-backend
  namespace: aichatbot
spec:
  selector:
    app: aichatbot-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
