apiVersion: v1
kind: Service
metadata:
  name: aichatbot-frontend
  namespace: aichatbot
spec:
  selector:
    app: aichatbot-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
