apiVersion: v1
kind: Secret
metadata:
  name: aichatbot-secrets
  namespace: aichatbot
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: aichatbot
  SPRING_DATASOURCE_PASSWORD: change-me
  MONGO_USER: admin
  MONGO_PASSWORD: change-me
  REDIS_PASSWORD: change-me
  POSTGRES_USER: aichatbot
  POSTGRES_PASSWORD: change-me
  POSTGRES_DB: aichatbot
  MONGO_DB: aichatbot
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: change-me
  OLLAMA_MODEL: llama3.1
